apiVersion: apps/v1
kind: Deployment
metadata:
 name: deployment1
spec:
  replicas: 4
  selector:
   matchLabels:
    app: deployment1
  template:
   metadata:
    labels:
     app: microservice
   spec:
    containers:
    - name: microservice
      image: 20150748/solar-system:latest
      ports:
      - containerPort: 3000