apiVersion: apps/v1
kind: Deployment
metadata:
 name: deployment1
spec:
  replicas: 4
  selector:
   matchLabels:
    app: microservice
  template:
   metadata:
    labels:
     app: microservice
   spec:
    containers:
    - name: microservice
      image: 20150748/solar-system:latest
      ports:
      - containerPort: 3000
      env:
      - name: NODE_ENV
        value: "production"
      livenessProbe:
        httpGet:
          path: /live
          port: 3000
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /ready
          port: 3000
        initialDelaySeconds: 5
        periodSeconds: 5
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"